2021-10-01 15:39:23,091 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting env: {}
2021-10-01 15:39:23,091 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-01 15:39:23,091 INFO    MainThread:116866 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153923-nazw9l7e/logs/debug.log
2021-10-01 15:39:23,091 INFO    MainThread:116866 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153923-nazw9l7e/logs/debug-internal.log
2021-10-01 15:39:23,092 INFO    MainThread:116866 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e22c9bf10>
2021-10-01 15:39:23,093 INFO    MainThread:116866 [wandb_init.py:init():375] calling init triggers
2021-10-01 15:39:23,093 INFO    MainThread:116866 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-01 15:39:23,093 INFO    MainThread:116866 [wandb_init.py:init():424] starting backend
2021-10-01 15:39:23,093 INFO    MainThread:116866 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-01 15:39:23,144 INFO    MainThread:116866 [backend.py:ensure_launched():135] starting backend process...
2021-10-01 15:39:23,190 INFO    MainThread:116866 [backend.py:ensure_launched():140] started backend process with pid: 122355
2021-10-01 15:39:23,191 INFO    MainThread:116866 [wandb_init.py:init():429] backend started and connected
2021-10-01 15:39:23,252 INFO    MainThread:116866 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-01 15:39:23,253 INFO    MainThread:116866 [wandb_init.py:init():477] updated telemetry
2021-10-01 15:39:23,253 INFO    MainThread:116866 [wandb_init.py:init():500] communicating current version
2021-10-01 15:39:28,254 INFO    MainThread:116866 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-01 15:39:32,947 INFO    MainThread:116866 [wandb_init.py:init():540] starting run threads in backend
2021-10-01 15:39:37,956 INFO    MainThread:116866 [wandb_run.py:_console_start():1601] atexit reg
2021-10-01 15:39:37,957 INFO    MainThread:116866 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-01 15:39:37,958 INFO    MainThread:116866 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-01 15:39:37,959 INFO    MainThread:116866 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-01 15:39:37,959 INFO    MainThread:116866 [wandb_init.py:init():565] run started, returning control to user process
2021-10-01 15:39:38,424 INFO    MainThread:116866 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-01 15:39:38,425 INFO    MainThread:116866 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-01 15:39:43,119 INFO    MainThread:116866 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-01 15:39:43,238 INFO    MainThread:116866 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-01 15:39:43,238 INFO    MainThread:116866 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-01 15:39:43,345 INFO    MainThread:116866 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting env: {}
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153943-3qch5x4p/logs/debug.log
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153943-3qch5x4p/logs/debug-internal.log
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:init():375] calling init triggers
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-01 15:39:43,353 INFO    MainThread:116866 [wandb_init.py:init():397] re-initializing run, found existing run on stack: nazw9l7e
2021-10-01 15:39:43,353 INFO    MainThread:116866 [wandb_run.py:finish():1271] finishing run ranuga-d/Waste-Classification/nazw9l7e
