2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting env: {}
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153943-3qch5x4p/logs/debug.log
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_153943-3qch5x4p/logs/debug-internal.log
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:init():375] calling init triggers
2021-10-01 15:39:43,352 INFO    MainThread:116866 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-01 15:39:43,353 INFO    MainThread:116866 [wandb_init.py:init():397] re-initializing run, found existing run on stack: nazw9l7e
2021-10-01 15:39:43,353 INFO    MainThread:116866 [wandb_run.py:finish():1271] finishing run ranuga-d/Waste-Classification/nazw9l7e
2021-10-01 15:39:43,354 INFO    MainThread:116866 [jupyter.py:save_history():353] not saving jupyter history
2021-10-01 15:39:43,354 INFO    MainThread:116866 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-01 15:39:43,354 INFO    MainThread:116866 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-10-01 15:39:43,354 INFO    MainThread:116866 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-10-01 15:39:43,354 INFO    MainThread:116866 [wandb_run.py:_restore():1543] restore
2021-10-01 15:39:43,472 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 720
}

2021-10-01 15:39:43,580 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 720
}

2021-10-01 15:39:44,476 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 720
}

2021-10-01 15:39:44,976 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,079 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,180 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,281 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,383 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,485 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,587 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,688 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 720
  total_bytes: 24609
}

2021-10-01 15:39:45,790 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8950
  total_bytes: 24609
}

2021-10-01 15:39:45,892 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9295
  total_bytes: 24609
}

2021-10-01 15:39:45,995 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,097 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,199 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,300 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,402 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,504 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:46,606 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:47,107 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:47,209 INFO    MainThread:116866 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24609
  total_bytes: 24609
}

2021-10-01 15:39:48,318 INFO    MainThread:116866 [wandb_run.py:_show_files():1915] logging synced files
2021-10-01 15:39:48,345 INFO    MainThread:116866 [wandb_init.py:init():424] starting backend
2021-10-01 15:39:48,345 INFO    MainThread:116866 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-01 15:39:48,348 INFO    MainThread:116866 [backend.py:ensure_launched():135] starting backend process...
2021-10-01 15:39:48,398 INFO    MainThread:116866 [backend.py:ensure_launched():140] started backend process with pid: 123338
2021-10-01 15:39:48,399 INFO    MainThread:116866 [wandb_init.py:init():429] backend started and connected
2021-10-01 15:39:48,409 INFO    MainThread:116866 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-01 15:39:48,410 INFO    MainThread:116866 [wandb_init.py:init():477] updated telemetry
2021-10-01 15:39:48,410 INFO    MainThread:116866 [wandb_init.py:init():500] communicating current version
2021-10-01 15:39:50,101 INFO    MainThread:116866 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-01 15:39:50,102 INFO    MainThread:116866 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-01 15:39:50,882 INFO    MainThread:116866 [wandb_init.py:init():540] starting run threads in backend
2021-10-01 15:39:55,888 INFO    MainThread:116866 [wandb_run.py:_console_start():1601] atexit reg
2021-10-01 15:39:55,889 INFO    MainThread:116866 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-01 15:39:55,889 INFO    MainThread:116866 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-01 15:39:55,889 INFO    MainThread:116866 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-01 15:39:55,889 INFO    MainThread:116866 [wandb_init.py:init():565] run started, returning control to user process
2021-10-01 15:40:32,414 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting env: {}
2021-10-01 15:40:32,414 INFO    MainThread:116866 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-01 15:40:32,414 INFO    MainThread:116866 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_154032-3j9sqii8/logs/debug.log
2021-10-01 15:40:32,414 INFO    MainThread:116866 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Waste-Classification/wandb/run-20211001_154032-3j9sqii8/logs/debug-internal.log
2021-10-01 15:40:32,415 INFO    MainThread:116866 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9e0c574a10>
2021-10-01 15:40:32,417 INFO    MainThread:116866 [wandb_init.py:init():375] calling init triggers
2021-10-01 15:40:32,417 INFO    MainThread:116866 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-01 15:40:32,417 INFO    MainThread:116866 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3qch5x4p
2021-10-01 15:40:32,418 INFO    MainThread:116866 [wandb_run.py:finish():1271] finishing run ranuga-d/Waste-Classification/3qch5x4p
